AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  Currencies2: 
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: 'Currencies2'
      AttributeDefinitions:
        - AttributeName: 'Code'
          AttributeType: 'S'
        - AttributeName: 'RetrievedStamp'
          AttributeType: 'N'
      KeySchema: 
        - AttributeName: 'Code'
          KeyType: 'HASH'
        - AttributeName: 'RetrievedStamp'
          KeyType: 'RANGE'
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    














































































































































































































