AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  Currencies: 
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: 'Currencies'
      AttributeDefinitions:
        - AttributeName: 'Code'
          AttributeType: 'S'
        - AttributeName: 'RetrievedStamp'
          AttributeType: 'N'
      KeySchema: 
        - AttributeName: 'Code'
          KeyType: 'HASH'
        - AttributeName: 'RetrievedStamp'
          KeyType: 'RANGE'
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  CurrencyServiceWorker:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CurrencyServiceWorker
      Runtime: nodejs10.x
      CodeUri: ./api
      Handler: currencyservice-worker.handler
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetCurrency:
          Type: Api
          Properties:
            Path: /currency/{code} 
            Method: get
  CurrencyServiceWorker:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CurrencyServiceWorker
      Runtime: nodejs10.x
      CodeUri: ./api
      Handler: currencyservicecompound-worker.handler
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetCurrency:
          Type: Api
          Properties:
            Path: /currency/{code}/{destinationCode} 
            Method: get
  HistoricCurrencyServiceWorker:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HistoricCurrencyServiceWorker
      Handler: index.handler
      Runtime: nodejs10.x
      CodeUri: ./api
      Handler: historiccurrencyservice-worker.handler
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetCurrency:
          Type: Api
          Properties:
            Path: /currency/{code}/Historic/{dateretrieved} 
            Method: get      
    














































































































































































































